### ISSUE TITLE
Make application work on all accounts.

### ISSUE THREAD

**Issue by khiltenb** [466-hmps/groupproject#21]
I went to try and host it locally, but the page would go straight to Hopper's public_html folder for the user designated by the URL. To fix this, we need to discuss architecture, and how we're gonna navigate the pages.

**Comment by Marrugaloo** [comment]
This was fixed in #20 commit https://github.com/466-hmps/groupproject/commit/c924383b94480f281063e4cdb3b187750caa76bc
